import type { Product } from "../src/types";

export const data: Product[] = [
	{
		imageName: "./images/image-01.jpg",
		category: "Collar",
		description: "description 01",
		name: "Golden Nebula",
		price: "150.000",
	},
	{
		imageName: "./images/image-02.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-03.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-04.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-05.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-06.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-07.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-08.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-09.jpg",
		category: "Areta",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-10.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-11.jpg",
		category: "Anillo",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-12.jpg",
		category: "Anillo",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-13.jpg",
		category: "Anillo",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-14.jpg",
		category: "Anillo",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-15.jpg",
		category: "Anillo",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-16.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-17.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-18.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-19.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-20.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-21.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-22.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-23.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-24.jpg",
		category: "Anillo",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-25.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-26.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-27.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-28.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-29.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-30.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-31.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-32.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-33.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-34.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-35.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-36.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-37.jpg",
		category: "Anillo",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-38.jpeg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-39.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-40.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-41.jpeg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-42.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-43.jpg",
		category: "Anillo",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-44.jpg",
		category: "Anillo",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-45.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-46.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-47.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-48.jpg",
		category: "Areta",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-49.jpeg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-50.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-51.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-52.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-53.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-54.jpeg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-55.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-56.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-57.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-58.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-59.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-60.jpg",
		category: "Anillo",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-61.jpg",
		category: "Areta",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-62.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-63.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-64.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-65.png",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-66.jpg",
		category: "Areta",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-67.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-68.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-69.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-70.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-71.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-72.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-73.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-74.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-75.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-76.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-77.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-78.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-79.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-80.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-81.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-82.jpg",
		category: "Anillo",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-83.jpg",
		category: "Anillo",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-84.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-85.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-86.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-87.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-88.jpg",
		category: "Pulsera",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-89.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
	{
		imageName: "./images/image-90.jpg",
		category: "Collar",
		description: "description 01",
		name: "Rose Gold",
		price: "160.000",
	},
];
